defaults:
  - _self_

dataset: 
  path: ${hydra:runtime.cwd}/data/
  yolo_dataset_folder: yolo_dataset
  view: actual
  save: false

output:
  path: ${hydra:runtime.cwd}/outputs/
  predicted_boxes_folder: predicted_boxes
  predicted_merged_boxes_folder: predicted_merged_boxes
  bounded_imgs_folder: bounded_imgs

algorithm:
  min_grid_block: 4
  max_grid_block: 20
  sliding_window_blocks: 4  
  